name: Publish Library

on:
  push:
    tags:
      - 'v*'  # This will trigger the pipeline for tags starting with "v", e.g., v1.0.0, v2.1.0, etc.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Grant execute permission for Gradlew
        run: chmod +x gradlew

      - name: Build Library
        run: ./gradlew build

      - name: Publish to GitHub Packages
        run: ./gradlew publish
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
